#!/usr/bin/env ruby

server_path = "bin/server"

filename = File.open(server_path, File::RDWR)

new_content = <<~content
    #!/bin/bash
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    parentdir="$(dirname "$DIR")"
    pid="$parentdir/tmp/pids/server.pid"
    if [ -f $pid ]; then
      rm $pid
    fi
    fuser -k -n tcp 3000
    export NODE_OPTIONS=--openssl-legacy-provider && rails server -b 0.0.0.0
  content

File.open(filename, "w") { |file| file << new_content }
